<Project>
  <Target Name="ValidateDatabaseSelection" BeforeTargets="CollectPackageReferences;PrepareForBuild">
    <Error Condition="'$(OpenBaseDatabase)' != 'postgres' and '$(OpenBaseDatabase)' != 'sqlserver' and '$(OpenBaseDatabase)' != 'oracle'"
           Text="OpenBaseDatabase must be postgres, sqlserver or oracle." />
  </Target>
</Project>
