// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenBaseNET.Infrastructure.Persistence;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace OpenBaseNET.Infrastructure.Persistence.Oracle.Migrations
{
    [DbContext(typeof(OpenBaseDbContext))]
    [Migration("20260926232145_InitialCustomers")]
    partial class InitialCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenBaseNET.Domain.Customers.Customer", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Id");

                    b.ToTable("CUSTOMERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
