<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../OpenBaseNET.Application/OpenBaseNET.Application.csproj" />
    <ProjectReference Include="../OpenBaseNET.Domain/OpenBaseNET.Domain.csproj" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Condition="'$(OpenBaseDatabase)' == 'postgres'" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Condition="'$(OpenBaseDatabase)' == 'sqlserver'" />
    <Compile Remove="Persistence/Postgres/**/*.cs" Condition="'$(OpenBaseDatabase)' != 'postgres'" />
    <Compile Remove="Persistence/SqlServer/**/*.cs" Condition="'$(OpenBaseDatabase)' != 'sqlserver'" />
  </ItemGroup>
</Project>
